### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by chinweokwu**
This milestone contains the Basic project structure of the app

### CODE REVIEW

**Review by trekab — COMMENTED** [review]
### Invalid! :stop_sign: 
Hi @chinweokwu! Unfortunately, I have to invalidate your code review request because you didn't set up linting as required. [Read more ...](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-#)

Please set up linting and submit another code review request.
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status:  Require changes :recycle: :traffic_light: 

Hi @chinweokwu, great job with setting up the linter :100: Also did well setting the app with "create-react-app" :+1: However, most of the requirements have not been met :slightly_smiling_face: Kindly check the comments below:
- Kindly delete the unnecessary files or assets; like the react svg logo, etc
- Kindly add a live link of the project to our README file. We currently do not have it
- I am unable to run the "npm start" command. Error: "module not found", can't resolve ".App.css". This is because we deleted the App.css file, so kindly go to "src/app.js" and remove the import line
- Kindly add big.js and prop-types to the package.json file
- Also, kindly improve the PR. PR is where we give a summary of the work we did in building the project

Once these are resolved  :smile: Kindly submit another code review request :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Comment by chinweokwu** [comment]
- fixed issues pointed out by Tse.
- I cannot work on the PR for now, because I have not completed the project

**Review by christianotieno — APPROVED** [review]
## Milestone Approved 🍾 
Hello @chinweokwu 👋 
Great job on this one 👍 
On to the next one 🥇 
### Happy coding 💻 
#### Christian Otieno (CR)

**Pull request merged**
