### PR TITLE
Completed

### PR DESCRIPTION
**Pull request by chinweokwu**
This branch contains the completed work of the MathMagician Project. In the project, we have 3 pages, the home page, calculator page and the quotes page.

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# Status: require changes :recycle: 

Great job Paul :clap: :+1: :100:, you are almost there you have match some requirements but you still need to add more :hammer: :hammer_and_wrench: :toolbox: unit tests.

Please check the comments below:
:point_down: :point_down: :point_down: :point_down: :point_down:

## Require Changes :red_circle:  

To consider the project 'complete' it must satisfy the following points:

* [x] all functionalities are testing using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/), `@testing-library/react`, see the [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/testing/useReactTestingLibrary.png) from [Pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106580952/).

* [x] all functions in calculate.js file are covered with unit tests

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_Feel free to contact me on slack if you have any questions or need help_
**_Zakariae El Mejdki_**

**Comment by chinweokwu** [comment]
I read and I understood the requriments. I feel I have done that with the use of mock. Mock testing i wrote literally do all that for you. Microverse requirements never stopped us from using mock for testing. Thank you.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required
Hi @chinweokwu :hand: 
Great job adding tests to your calculator app. But we also need to test the calculator functionalities.

- [x] Your tests successfully assure that react components are being properly displayed. However, as said in the requirements we also need to test the calculator functionalities. We need to write tests to verify if each operation (addition, subtraction, multiplication...) and buttons are working as expected.
Screenshot from 2021-02-25 12-02-25

Happy coding :computer: 
**Sérgio Torres**

**Comment by chinweokwu** [comment]
- Calculator functionality tested

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @chinweokwu, congratulations on fixing the comments outlined by the previous TSE's :muscle: Awesome. However, there are a few failing tests I have a screenshot below which will help us to fix the test. Kindly check the comment below:

- Kindly fix the failing test as in the screenshot below
fg

Once this is fixed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by bellom — APPROVED** [review]
## Hi @chinweokwu  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
